[package]
name = "host-light-client"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.2.3", features = ["metal"]}
winternitz-core = { path = "../core" }


[features]
metal = ["risc0-zkvm/metal"]
